### ISSUE TITLE
为 Envoy Go 扩展建设插件市场

### ISSUE THREAD

**Issue by jizhuozhi** [mosn/envoy-golang-filter-hub#1]
## 项目描述：

Envoy是当前最流行的网络代理之一，Go扩展是MOSN社区为Envoy增加的Go生态基础，也是MoE框架的基础。

受益于Golang生态系统，研发可以轻松在Envoy实现插件用于更多的长尾场景，其中很多场景都是通用的。

本项目是为Envoy GO扩展构建插件市场。在插件市场中，人们可以在插件市场中贡献他们已经建设好并已经在生产环境中使用的优质插件，并由其他人来使用。通过插件市场，可以让Envoy生态变得更加开放、共享、丰富

## 项目产出要求

1. 提供一个Envoy GO插件的内容平台，在这里可以发布经过社区review的优秀插件，需要拥有服务端与前端页面
2. 不自建账号体系，通过GitHub OAuth2.0完成用户认证与授权
3. 对接GitHub OpenAPI，支持动态获取插件所在仓库信息，包括README，分支版本以及star数

**Comment by cyb0225** [comment]
我可以理解成类似 docker hub 那种类型的插件市场，数据和仓库来源 github

**Comment by jizhuozhi** [comment]
是的，只不过我们不准备自建账号体系，因为这在开源社区会有数据安全级别信任的问题，所以我们准备使用OAuth2.0来对接这些认证与授权提供商，除非有一天由专门的机构来运营这个hub

**Comment by nickxudotme** [comment]
你好哇👋，我对这个项目很感兴趣，目前想到了一些问题

## 插件需要存储哪些信息？
首先关于插件的一些元数据例如名称、仓库地址、作者、描述、版本号、标签等肯定是要存的
另外，这个插件的本质是能够通过源码编译的 `so` 文件，为了保证稳定性，我们是否应该存储每一版发布的插件源码和构建后的 `so` 文件？

## 插件上传后需要审核吗？
为确保上传的插件没有恶意代码或漏洞，“经过社区review” 是不是指会有一批人来对插件进行人工审查？

**Comment by jizhuozhi** [comment]
> 另外，这个插件的本质是能够通过源码编译的 so 文件，为了保证稳定性，我们是否应该存储每一版发布的插件源码和构建后的 so 文件？

本质上，插件开发者要分发的内容都是相同的：一个二进制，你说的没错，目前go插件都是通过so来部署的。那么就牵扯到了如何分发这个二进制的问题。我们不准备额外建立存储机制，市面上有非常多设计的高质量的分发格式。而在云原生环境，我们一定最熟悉docker image，它本质也是符合OCI规范的bundle。OCI规范定义了bundle的分层文件系统，制品diff，以及其他原数据等。如果从scratch开始构建，那么我们就可以得到仅包含制品的bundle。

与此同时，云原生生态对OCI规范支持的非常成熟，如docker hub，gcr等等，以及内网环境下的私有制品仓库等等，通过OCI我们可以无需额外解决分发的问题。

至于说审核机制，这是非常好的问题，我认为GitHub的PR工作流就足够完美，所有人都可以对PR进行Review，给出自己的建议，然后由具有特定权限的人来合并它。我们可以参考或直接使用GitHub作为我们的工作流引擎

**Comment by nickxudotme** [comment]
嗯嗯，将插件打包成 Docker Image ，同时使用 GitHub 的工作流来审核的确是不错的选择

我突然想到，我们要实现的这个流程好像和在 GitHub Marketplace 中发布自己写的 GitHub Actions 有点像

比方说，随便拿一个 GitHub Actions 来说

- 这是它的 repo ：https://github.com/reviewdog/action-golangci-lint
- 这是它在 GitHub Marketplace 上的页面： https://github.com/marketplace/actions/run-golangci-lint-with-reviewdog

我感觉这大概就是我们最后要实现的效果

---

在翻了一些官方文档 [^1] [^2]  和视频 [^3] 之后，我大概了解到这些信息：

- 上传和更新自己的 Actions 不需要官方审核，只需要同意一份开发人员协议
- 具体的流程大概如下：
  1. 创建一个公共的 reop，在里面完成自己的 Actions 功能，
  2. 在根目录创建一个 `action.yaml` 来交代一些元数据，包括名称、作者、本 Actions 的入参和出参列表
  3. 按照正常的流程创建一个 Release ，同时勾上发布到市场，并选择分区
  4. 然后你就能在 Marketplace 上看见自己的 Actions 了

而对于我们的项目而言，需要有一个 Review 的流程，我想了一下，不知道这样合不合适：

- 首先还是在个人名下的仓库开发好
- 然后如果要发布的话，需要申请加入开发插件的 organization  （在这一步可以让用户同意开发协议，也可以验证发布者的身份
- 接着申请将 repo 移交到这个组织里，如果完成就算发布了（这一步需要管理员来审核，并最后由后端调用 API 操作
- 后端自动在组织里面的项目设置一些分支保护规则，比方说只能由管理员 team 来合并 PR （需要管理员审核新的提交，大概就是这个意思

而后端会自动更新组织中的仓库信息给前端展示，这可以使用两种方式：通过 GitHub API 轮询抓取或是通过 GitHub Actions 自动上报

关于二进制的打包分发，可以在后端建立一套工作流对每个发布版本构建并推送镜像，或者也可以在 GitHub Actions 中自动完成

至于存储介质，我记得 Docker Hub 好像对组织的仓库开始收费了，不知道有哪些更好的方案（这方面我其实没有太多了解

---

以上是我本人目前的一些想法，不知道是否合理  :)


[^1]:  [关于 GitHub Marketplace - GitHub 文档](https://docs.github.com/zh/apps/publishing-apps-to-github-marketplace/github-marketplace-overview/about-github-marketplace) 
[^2]: [在 GitHub Marketplace 中发布操作 - GitHub 文档](https://docs.github.com/zh/actions/creating-actions/publishing-actions-in-github-marketplace)
[^3]: [Create and Publish custom GitHub Actions | #AzureHappyHours - YouTube](https://www.youtube.com/watch?v=UO4qGXD-O1o)

**Comment by jizhuozhi** [comment]
非常不错的流程设计，基本上覆盖到了这个项目的所有的核心功能包括如何更好的进行社区共建

> 后端自动在组织里面的项目设置一些分支保护规则，比方说只能由管理员 team 来合并 PR （需要管理员审核新的提交，大概就是这个意思

因为很多开源项目制品仓库都经历过供应链投毒事件，因此不可变基础设施变的非常重要，所以最终发版一定是由组织成员（或开源社区共建成员）来执行的，并且使用SHA1作为唯一标识的。在企业开发非常关键的一点就是审计，所有的操作都要有所记录，而在开源社区也要有这样的机制（可能只是需要某些关键节点）。

> 而后端会自动更新组织中的仓库信息给前端展示，这可以使用两种方式：通过 GitHub API 轮询抓取或是通过 GitHub Actions 自动上报

这里有很多种方式可以实现，从公网带宽的角度，我倾向于GitHub Actions这种基于事件的触发机制。同时，发版后的分支通常都是稳定的，而使用插件的开发者通常不会太关注snapshot的分支，所以这里没有必要使用后端轮询抓取

**Comment by jizhuozhi** [comment]
开源之夏学生报名已经开始，有兴趣的学生可以报名参加开源之夏加入我们，在这个项目的过程中我们会将我们的经验倾囊相授~ https://summer-ospp.ac.cn/org/prodetail/23f080259?list=org&navpage=org

**Comment by ligen131** [comment]
Hello👋我对这个项目非常感兴趣。基于上面同学的方案和讨论，我初步提出修改后的构想：

首先社区需要做的：

1. 插件首次提交的 review 方式。对这一点我有 2 个备选方案：
   1. 在插件市场中包含新插件申请系统和新插件 Review 系统。
   2. 直接使用 GitHub Pull Request。社区新建插件申请仓库并攥写指南，开发者通过在该仓库提 PR 的方式提交插件申请，申请通过则该插件自动加入插件市场。
2. 后续开发 review 方式：开发 GitHub Actions，要求开发者仓库使用该 Actions，在每次开发者发布 Release 时自动向插件市场后台提交 review 申请。后端只需存储上一次该仓库审核通过的 commit SHA1 值与 release 版本号即可，且无需处理二进制文件存储的问题（存储于 GitHub）。

开发者申请流程：

1. 在个人 Public repo 中开发完成，并根据社区提供的模板在仓库中添加 `plugin.yml` 作为项目元数据与基本情况的介绍存放文件。
2. 开发者在仓库中添加社区开发的 GitHub Actions 以在每次 release 时自动提交 review 申请。
3. 开发者在插件市场页面填写项目信息，或在插件申请仓库提 PR，等待管理员处理。
4. 每次发布新版本时只需在本仓库直接 release 即可，等待社区管理员审核；若审核不通过则以邮件通知。
